services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    volumes:
      - ollama:/root/.ollama
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 11434
